// ---------------------------------------------------------------------------
// MOCK resume representation.
//
// There is no real resume-generation system in this prototype yet. This
// produces a plain-text resume from a candidate's mock profile purely for
// demonstration ("Download Resume" needs to do *something* real). It is
// intentionally isolated here so a real Resume Generation system can replace
// just this one function later without touching any page that calls it.
// ---------------------------------------------------------------------------

import type { MockCandidate } from "./candidates";

export function generateMockResumeText(candidate: MockCandidate): string {
  const lines: string[] = [
    candidate.name,
    candidate.headline,
    `${candidate.location} · ${candidate.workMode}`,
    "",
    "ABOUT",
    candidate.about,
    "",
    "SKILLS",
    candidate.skills.join(", "),
    "",
    "PROJECTS",
    ...candidate.projects.flatMap((p) => [
      `${p.title} (${p.technologies.join(", ")})`,
      p.description,
      "",
    ]),
    "LEARNING",
    `${candidate.courseName} — ${candidate.courseComplete ? "Completed" : "In Progress"}`,
    ...candidate.completedSubjects.map((s) => `- ${s}`),
    "",
    "ACHIEVEMENTS",
    ...candidate.achievements.map((a) => `- ${a}`),
    "",
    "— Generated by NextStep² (demo resume — not a real document store)",
  ];
  return lines.join("\n");
}

/** Triggers a browser download of the candidate's mock resume as a .txt file. */
export function downloadMockResume(candidate: MockCandidate) {
  const text = generateMockResumeText(candidate);
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${candidate.name.replace(/\s+/g, "-")}-resume.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
